print ("How old are you:",end='')
age=input()
print("How tall are you:", end='')
height=input()
print("how much do you weight:",end='')
weight=input()
print (f"so you are {age} old,{height} tall and {weight} lbs heavy")
